FUNCTION Z_SMERP_PM_WORKORD_GET.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IS_BAPI_INPUT) TYPE  /SYCLO/CORE_BAPI_INPUT_STR OPTIONAL
*"  EXPORTING
*"     VALUE(ES_BAPI_OUTPUT) TYPE  /SYCLO/CORE_BAPI_OUTPUT_STR
*"  TABLES
*"      IT_ARBPL_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_AUART_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_TPLNR_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_EQUNR_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_GLTRS_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_STORT_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_MSGRP_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_STREET_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_CITY_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_IPHAS_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      IT_PRIOK_RA STRUCTURE  /SYCLO/CORE_RANGE_STR OPTIONAL
*"      ET_WORKORD_SRCH STRUCTURE  ZSMERP_PM_WORKORD_SRCH_STR OPTIONAL
*"      ET_RETURN STRUCTURE  BAPIRET2 OPTIONAL
*"----------------------------------------------------------------------

************************************************************************
* Template Section
************************************************************************

  INCLUDE /syclo/core_bapi_template_incl.

ENDFUNCTION.
